/* eslint-disable */
/**
 * Search - Search TV Shows
 * GET /search/tv API: https://developers.themoviedb.org/3/search/search-tv-shows
 *
 * response header 'cache-control': 'public, max-age=120' --- 2 minutes
 *
 * below example with query: "fox", and page: 1
 */
export const mockSearchTvShowsResponse = {
  page: 1,
  results: [
    {
      backdrop_path: null,
      first_air_date: '1996-04-28',
      genre_ids: [10763],
      id: 2092,
      name: 'Fox News Sunday',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Fox News Sunday',
      overview:
        'Fox News Sunday with Chris Wallace is a Sunday morning news/talk show on the Fox Broadcasting Company; since 2003, Fox News Sunday has been hosted by Chris Wallace.',
      popularity: 15.623,
      poster_path: null,
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: null,
      first_air_date: '1984-12-30',
      genre_ids: [35, 18],
      id: 7208,
      name: 'Crazy like a Fox',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Crazy like a Fox',
      overview:
        'Crazy Like a Fox is an American television series set in San Francisco, California, that aired on CBS from December 30, 1984 to May 3, 1986.',
      popularity: 5.331,
      poster_path: null,
      vote_average: 9,
      vote_count: 2,
    },
    {
      backdrop_path: null,
      first_air_date: '2013-09-26',
      genre_ids: [35],
      id: 58942,
      name: 'The Michael J. Fox Show',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'The Michael J. Fox Show',
      overview:
        'Look who’s making the news again! One of NY’s most beloved news anchors, Mike Henry (Michael J. Fox), put his career on hold to spend more time with his family and focus on his health after he was diagnosed with Parkinson’s. But now five years later, with the kids busy growing up and Mike growing restless, it just might be time for him to get back to work. Having never wanted Mike to leave in the first place, his old boss Harris Green jumped at the chance to get him back on TV. The trick, as it’s always been, was to make Mike think it was his idea. After several – okay, many - failed attempts, Mike’s family, anxious to see him out of the house, finally succeeded in getting him to “run into” Green. Now their plan is in motion. He’ll be back to juggling home, family, and career, just like the old days – only better.',
      popularity: 5.79,
      poster_path: '/9oaOg8OzWo71zAYrsqoS3N3vYon.jpg',
      vote_average: 5.6,
      vote_count: 37,
    },
    {
      backdrop_path: null,
      first_air_date: '',
      genre_ids: [10763],
      id: 715,
      name: 'Fox & Friends',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Fox & Friends',
      overview:
        'Fox & Friends is an early-morning opinion talk show that begins at 6:00 a.m. Eastern Time with the latest Fox News Live headlines and news of the morning. It continues with a variety of segments including interviews, updates of news stories with correspondents, analysis from the hosts, and entertainment segments. The show has a list of regular contributors, including Dr. Manny Alvarez, presenting his health segments "Ask Dr. Manny" and "Dr. Manny\'s Healthbeat."',
      popularity: 2.264,
      poster_path: '/rUSI6wmB6Vsyg65nyVaWSPwSrP3.jpg',
      vote_average: 2,
      vote_count: 6,
    },
    {
      backdrop_path: null,
      first_air_date: '1955-10-05',
      genre_ids: [18],
      id: 10642,
      name: 'The 20th Century Fox Hour',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'The 20th Century Fox Hour',
      overview:
        'The 20th Century Fox Hour is an American drama anthology series televised in the United States on CBS from 1955 to 1957. Some of the shows in this series were restored, remastered and shown on the Fox Movie Channel in 2002 under the title Hour of Stars. The season one episode Overnight Haul, starring Richard Conte and Lizabeth Scott, was released in Australia as a feature film.',
      popularity: 5.881,
      poster_path: null,
      vote_average: 1,
      vote_count: 1,
    },
    {
      backdrop_path: null,
      first_air_date: '1980-03-10',
      genre_ids: [18],
      id: 9654,
      name: 'Fox',
      origin_country: ['GB'],
      original_language: 'en',
      original_name: 'Fox',
      overview:
        'Fox is a British television drama series produced by Euston Films and Thames Television for the ITV network in 1980.\n\nThe thirteen-part series was based around the lives of the titular Fox family, who lived in London and had gangland connections.\n\nThe series was written by Trevor Preston, produced by Verity Lambert and directed by Jim Goddard.',
      popularity: 1.498,
      poster_path: null,
      vote_average: 6,
      vote_count: 1,
    },
    {
      backdrop_path: '/2QLhzvBN8FmIyWDFToQhEhdNlzj.jpg',
      first_air_date: '2017-04-05',
      genre_ids: [35, 18],
      id: 82437,
      name: "The Fox's Summer",
      origin_country: ['CN'],
      original_language: 'zh',
      original_name: "The Fox's Summer",
      overview:
        "Gu Chengze, the adopted son of the Gu family, is the CEO of Gu Mall Corporation. Mrs. Gu wishes for her biological grandson, Gu Jinyu to take over the company; and Gu Chengze is tasked to guide the rightful heir towards becoming a respectful businessman. During this time, he meets fashion designer Li Yanshu and discovers that she is Gu Jinyu's ex-girlfriend. He decides to hire her aboard to motivate Gu Jinyu, who still harbors feelings for Li Yanshu. The plan worked on when Gu Jinyu decides to join the company and pursue her. When Mrs. Gu finds out about Gu Jinyu's feelings for Li Yanshu, she was livid and tells Gu Chengze to separate the both of them. This creates an opportunity for Gu Chengze and Li Yanshu to get closer to each other, and they fell in love. With the help of Li Yanshu, Gu Chengze overcomes many difficult situations. Gu Jinyu, after undergoing life-changing experiences, also matures and successfully took over his company.",
      popularity: 16.008,
      poster_path: '/9RdKkh5C7JpwdZfHIEz9Rov6oEG.jpg',
      vote_average: 10,
      vote_count: 1,
    },
    {
      backdrop_path: '/8JPiLDiXiOkUxh22BKUwkSXOXRt.jpg',
      first_air_date: '2001-02-05',
      genre_ids: [80],
      id: 36580,
      name: 'Fox Grønland',
      origin_country: ['NO'],
      original_language: 'en',
      original_name: 'Fox Grønland',
      overview:
        'The series is about police investigators in Greenland police and the assignments they receive. Every day they face new challenges that affect them differently. These consist of inspector Jan Erik Holm, Hassan Mohammed Arif Osman, Trond Olsen and Holms ex-wife Cecilie Melvold. The series paints a somewhat grim picture of Oslo, it is a place where no one is safe, where nobody is above threats and blackmail. Even policemen are subjected to harassment.',
      popularity: 0.951,
      poster_path: '/1wxdL7A100pT7mJ8YN9TDbgKEgS.jpg',
      vote_average: 6,
      vote_count: 1,
    },
    {
      backdrop_path: null,
      first_air_date: '',
      genre_ids: [],
      id: 115393,
      name: 'FOX DVD',
      origin_country: [],
      original_language: 'fr',
      original_name: 'FOX DVD',
      overview: '',
      popularity: 1.25,
      poster_path: null,
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: null,
      first_air_date: '1959-10-23',
      genre_ids: [],
      id: 20149,
      name: 'The Swamp Fox',
      origin_country: [],
      original_language: 'en',
      original_name: 'The Swamp Fox',
      overview:
        'The story of Revolutionary War hero Francis Marion, an American patriot who fought the British Tories using unusual methods, becoming known as “The Swamp Fox.”',
      popularity: 1.627,
      poster_path: null,
      vote_average: 5,
      vote_count: 2,
    },
    {
      backdrop_path: null,
      first_air_date: '1995-07-28',
      genre_ids: [37],
      id: 74172,
      name: 'Black Fox',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Black Fox',
      overview:
        'A former slave affects peace between Indian tribes and homesteaders in 1860s West Texas.',
      popularity: 0.929,
      poster_path: '/vtil3nCEymiJ4ALsXxurh66BBgi.jpg',
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: null,
      first_air_date: '',
      genre_ids: [],
      id: 24158,
      name: 'Fox After Breakfast',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Fox After Breakfast',
      overview: '',
      popularity: 1.34,
      poster_path: null,
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: null,
      first_air_date: '',
      genre_ids: [],
      id: 71469,
      name: 'Canal Fox',
      origin_country: [],
      original_language: 'pt',
      original_name: 'Canal Fox',
      overview: '',
      popularity: 0.6,
      poster_path: null,
      vote_average: 10,
      vote_count: 1,
    },
    {
      backdrop_path: null,
      first_air_date: '',
      genre_ids: [],
      id: 22375,
      name: 'Fox and Friends',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Fox and Friends',
      overview: '',
      popularity: 0.6,
      poster_path: null,
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: '/lKZx3YDrJHGEZD5P1t5PM0fFuzf.jpg',
      genre_ids: [10763],
      id: 94,
      name: 'Fox Online',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Fox Online',
      overview: 'Fox Online was an American talk/ news program on the Fox News Channel.',
      popularity: 0.654,
      poster_path: '/3G6MCvgHAjP6zVZYQT93TiTp3ry.jpg',
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: null,
      first_air_date: '2001-10-27',
      genre_ids: [],
      id: 25553,
      name: 'Fox and Cotton Candy',
      origin_country: [],
      original_language: 'en',
      original_name: 'Fox and Cotton Candy',
      overview:
        '《여우와 솜사탕》은 2001년 10월 27일부터 2002년 4월 27일까지 방영된 MBC 주말연속극으로, 《그 여자네 집》 후속으로 방영되었다.',
      popularity: 1.091,
      poster_path: null,
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: null,
      first_air_date: '1991-12-08',
      genre_ids: [18],
      id: 77683,
      name: 'Red Fox',
      origin_country: ['GB'],
      original_language: 'en',
      original_name: 'Red Fox',
      overview: 'Miniseries based on the novel by Gerald Seymour.',
      popularity: 0.6,
      poster_path: null,
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: null,
      first_air_date: '',
      genre_ids: [],
      id: 56732,
      name: 'Fox Field',
      origin_country: [],
      original_language: 'en',
      original_name: 'Fox Field',
      overview: '',
      popularity: 0.6,
      poster_path: null,
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: null,
      genre_ids: [],
      id: 2300,
      name: 'Fox Report',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Fox Report',
      overview:
        'The Fox Report was an American nightly news program on Fox News Channel, hosted weekdays by Shepard Smith and weekends by Harris Faulkner.',
      popularity: 0.6,
      poster_path: null,
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: null,
      first_air_date: '',
      genre_ids: [],
      id: 15034,
      name: 'Fox cartoons',
      origin_country: [],
      original_language: 'en',
      original_name: 'Fox cartoons',
      overview:
        'Fox cartoons refers to animated television series presented by the American TV network Fox Broadcasting Company. During the more than twenty-year existence of the Network, there have been many successful prime time animated series and Fox cartoons. The first and most famous of these, The Simpsons, was the first such series since the end of The Flintstones in the 1960s.',
      popularity: 0.6,
      poster_path: null,
      vote_average: 0,
      vote_count: 0,
    },
  ],
  total_pages: 6, // 20 items per page
  total_results: 117,
};

// below example with query: "test123", and page: 1
export const mockSearchTvShowsEmptyResponse = {
  page: 1,
  results: [],
  total_results: 0,
  total_pages: 0,
};

export const mockSearchTvShows401Response = {
  status_code: 7,
  status_message: 'Invalid API key: You must be granted a valid key.',
  success: false,
};

// 404 response
export const mockSearchTvShows404Response = {
  success: false,
  status_code: 34,
  status_message: 'The resource you requested could not be found.',
};

// no query provided
export const mockSearchTvShows422Response = {
  errors: ['query must be provided'],
};
