/* eslint-disable */
/**
 * Search - Search Movies
 * GET /search/movie API: https://developers.themoviedb.org/3/search/search-movies
 *
 * response header 'cache-control': 'public, max-age=120' --- 2 minutes
 *
 * below example with query: "fox", and page: 1
 */
export const mockSearchMoviesResponse = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/tJRbPH8Q0divR3UkdpVxmNcd1YE.jpg',
      genre_ids: [12, 16, 35, 10751],
      id: 9948,
      original_language: 'en',
      original_title: 'The Fox and the Hound 2',
      overview:
        'Best friends Tod, a fox kit, and Copper, a hound puppy, visit a country fair when they see a band of dogs called "The Singin\' Strays". The band has five members: Dixie, Cash, Granny Rose, and twin brothers Waylon and Floyd. It is important that they perform well because a talent scout is visiting.',
      popularity: 146.193,
      poster_path: '/mIhKia4eMOBCYgHSHLHXQ01oc2A.jpg',
      release_date: '2006-11-09',
      title: 'The Fox and the Hound 2',
      video: false,
      vote_average: 5.9,
      vote_count: 413,
    },
    {
      adult: false,
      backdrop_path: '/87uShMszqPxwA034GsskGdzJOgN.jpg',
      genre_ids: [12, 16, 18, 10751],
      id: 10948,
      original_language: 'en',
      original_title: 'The Fox and the Hound',
      overview:
        'When a feisty little fox named Tod is adopted into a farm family, he quickly becomes friends with a fun and adorable hound puppy named Copper. Life is full of hilarious adventures until Copper is expected to take on his role as a hunting dog -- and the object of his search is his best friend!',
      popularity: 55.22,
      poster_path: '/1382VHxqZDXu2t8i46zf4fP71JG.jpg',
      release_date: '1981-07-10',
      title: 'The Fox and the Hound',
      video: false,
      vote_average: 7.1,
      vote_count: 2312,
    },
    {
      adult: false,
      backdrop_path: '/zuhBQ0SEFuKzZufaZ7IatYodPtE.jpg',
      genre_ids: [12, 16, 35, 10751],
      id: 10315,
      original_language: 'en',
      original_title: 'Fantastic Mr. Fox',
      overview:
        'The Fantastic Mr. Fox bored with his current life, plans a heist against the three local farmers. The farmers, tired of sharing their chickens with the sly fox, seek revenge against him and his family.',
      popularity: 24.293,
      poster_path: '/njbTizADSZg4PqeyJdDzZGooikv.jpg',
      release_date: '2009-10-23',
      title: 'Fantastic Mr. Fox',
      video: false,
      vote_average: 7.7,
      vote_count: 3289,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [53, 80],
      id: 666509,
      original_language: 'en',
      original_title: 'Fox Hunt Drive',
      overview:
        'Alison, a down-on-her-luck young professional, spends her evenings trying to make ends meet as a rideshare driver. Wrapping her shift, she decides to take on one last passenger — only to find herself in unexpected danger when she discovers the mysterious stranger is not what he appears to be. Through a twisted turn of events, Alison must turn to her enigmatic passenger for help and is now stuck with him. In over her head, Alison must fight to get through the night covering her tracks, avoiding the police, and discovering who her inscrutable passenger truly is.',
      popularity: 5.578,
      poster_path: '/sq8kqES1Z17Hsa0ppmp65AJV6eD.jpg',
      release_date: '2020-03-06',
      title: 'Fox Hunt Drive',
      video: false,
      vote_average: 10,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: '/bfXekAz6OzhbbVFnYOobiSEXG9O.jpg',
      genre_ids: [27],
      id: 430993,
      original_language: 'en',
      original_title: 'Fox Trap',
      overview:
        'After a terrible accident leaves a young girl disabled, five years later, the group responsible are invited to a remote manor house in the countryside for a class reunion. Little do they know, they are being targeted by a masked maniac hell bent on revenge.',
      popularity: 3.765,
      poster_path: '/9SchiYEqePQCD9eGiB6R0NeGeO8.jpg',
      release_date: '2016-12-31',
      title: 'Fox Trap',
      video: false,
      vote_average: 4.9,
      vote_count: 7,
    },
    {
      adult: false,
      backdrop_path: '/twcVnPcpdOQW6NWCEl09Jbp6qrT.jpg',
      genre_ids: [35],
      id: 711850,
      original_language: 'en',
      original_title: 'The Fox Hunter',
      overview:
        'A prominent Southern family of savage media moguls deteriorates at the crossroads of past and progress in matters of death, wealth, love, and American journalism.',
      popularity: 4.718,
      poster_path: '/nZNmYW6bax1MpQ8hcTdB8ioSWeC.jpg',
      release_date: '2020-06-05',
      title: 'The Fox Hunter',
      video: false,
      vote_average: 5.3,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: '/sQRqZ4s7KHl2uHg5dm2CGm0BZgI.jpg',
      genre_ids: [80, 35],
      id: 19137,
      original_language: 'en',
      original_title: 'After the Fox',
      overview:
        "Criminal mastermind 'The Fox' sets up a phony film production and masquerades as it's director as part of a plan to smuggle a stolen gold shipment into Italy.",
      popularity: 4.645,
      poster_path: '/n66MJNKW51LtyoE7OvsZ2oau3x2.jpg',
      release_date: '1966-01-01',
      title: 'After the Fox',
      video: false,
      vote_average: 6,
      vote_count: 36,
    },
    {
      adult: false,
      backdrop_path: '/2BMrEJ6BJWAKMifz28L28gOABYb.jpg',
      genre_ids: [18, 53],
      id: 475323,
      original_language: 'en',
      original_title: 'The Fox',
      overview:
        'The Fox tells the story of The Hague-based Europol agent Simon Fox (Morgan C Jones). He leads a troubled life after he accidentally shot and killed a child. Struggling with this trauma Simon is confronted with a secret post-war resistance organization called ‘Gladio’. The organization is abused by illustrious politicians in their hunger for power, as a result of which The Netherlands is likely to degenerate into a police state. When it becomes clear that Simon’s father established ‘Gladio’ after the war with very different intentions, Simon is determined to turn the tide..',
      popularity: 2.725,
      poster_path: '/uvEteXJoWScLNj9HRmrl50ceYJg.jpg',
      release_date: '2017-09-21',
      title: 'The Fox',
      video: false,
      vote_average: 5.4,
      vote_count: 5,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 53],
      id: 22155,
      original_language: 'hi',
      original_title: 'Fox',
      overview:
        'Fox is an edge-of-the-seat suspense thriller that moves at high speed between the bustling metropolis of Bombay and the beautiful beaches of Goa.',
      popularity: 2.223,
      poster_path: '/cddhNK23HaP85IOc6TE3Zp7A389.jpg',
      release_date: '2009-09-04',
      title: 'Fox',
      video: false,
      vote_average: 4.4,
      vote_count: 5,
    },
    {
      adult: false,
      backdrop_path: '/vbqtgD1upkZEWaKeycW0SjPP4H2.jpg',
      genre_ids: [35, 37],
      id: 54613,
      original_language: 'en',
      original_title: 'The Duchess and the Dirtwater Fox',
      overview:
        'A female hustler is chasing after rich men, but becomes repeatedly mixed up with a suave con man and card shark through a series of misadventures before falling in love with him.',
      popularity: 6.009,
      poster_path: '/lqxOQ38oVyCC78iROrF1T9qL47q.jpg',
      release_date: '1976-04-01',
      title: 'The Duchess and the Dirtwater Fox',
      video: false,
      vote_average: 6,
      vote_count: 28,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 74896,
      original_language: 'en',
      original_title: 'The Fox',
      overview:
        'Ellen and Jill who live a quiet life on a farm in rural Canada are surprised by the visit of a former tenant’s grandson.',
      popularity: 2.379,
      poster_path: '/ao4HnqtKMbLLK2USSnK1gEbNTCb.jpg',
      release_date: '1967-12-13',
      title: 'The Fox',
      video: false,
      vote_average: 6.5,
      vote_count: 9,
    },
    {
      adult: false,
      backdrop_path: '/ezfezjXNPKTFMFCpsAyoHQdozjq.jpg',
      genre_ids: [28, 18, 36, 10752],
      id: 26205,
      original_language: 'en',
      original_title: 'The Desert Fox: The Story of Rommel',
      overview:
        'The life and career of Erwin Rommel and his involvement in the plot to assassinate Hitler.',
      popularity: 8.162,
      poster_path: '/kxGb2G3sW1au1biz9hHwJQb6w99.jpg',
      release_date: '1951-10-16',
      title: 'The Desert Fox: The Story of Rommel',
      video: false,
      vote_average: 6.5,
      vote_count: 51,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [16, 10751],
      id: 69101,
      original_language: 'en',
      original_title: 'The Fox Hunt',
      overview:
        'Donald controls the hounds , and Goofy is riding on Horace Horsecollar, as the fox outwits both of them.',
      popularity: 3.454,
      poster_path: '/kC5mx6APyqyayPB8F5wfebQMXM7.jpg',
      release_date: '1938-07-29',
      title: 'The Fox Hunt',
      video: false,
      vote_average: 5.9,
      vote_count: 23,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 336157,
      original_language: 'en',
      original_title: 'Murnau, Borzage and Fox',
      overview:
        'Documentary focusing on the film careers F.W. Murnau, Frank Borzage and William Fox and their impact on the history of cinema.',
      popularity: 3.009,
      poster_path: null,
      release_date: '2008-12-09',
      title: 'Murnau, Borzage and Fox',
      video: false,
      vote_average: 5.7,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 115418,
      original_language: 'en',
      original_title: 'Black Fox',
      overview:
        'A former slave affects peace between Indian tribes and homesteaders in 1860s West Texas.',
      popularity: 2.013,
      poster_path: '/ugDohDnrVU2742JNKnmrpLFxMaj.jpg',
      release_date: '1995-07-28',
      title: 'Black Fox',
      video: false,
      vote_average: 4,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: '/5m3iuO5ACGuOE15Gv1TXmNweXRK.jpg',
      genre_ids: [28, 37],
      id: 42136,
      original_language: 'en',
      original_title: 'The Grey Fox',
      overview:
        'Old West highwayman Bill Miner, known to Pinkertons as "The Gentleman Bandit," is released in 1901 after 33 years in prison, a genial and charming old man. Entering a world unfamiliar to him, he returns to the only thing that gives him purpose — robbery.',
      popularity: 2.934,
      poster_path: '/bCnuMKTYw92gYQ8dtlgUjkNOQog.jpg',
      release_date: '1982-12-16',
      title: 'The Grey Fox',
      video: false,
      vote_average: 6.9,
      vote_count: 15,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [80, 18, 53],
      id: 412215,
      original_language: 'en',
      original_title: 'Fox',
      overview:
        'The trials and tribulations of the Fox family of London, a clan with gangland connections.',
      popularity: 1.4,
      poster_path: null,
      release_date: '1980-03-10',
      title: 'Fox',
      video: false,
      vote_average: 1,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 227061,
      original_language: 'en',
      original_title: 'Fox Trot Finesse',
      overview:
        "Ferdie's wife is fox-trot crazy, wanting to go dancing all the time. To get out of it, Ferdie fakes an ankle injury. When his wife spies him walking without his crutch, she writes a letter to her stern mother, inviting her to stay with them while Ferdie heals. Rather than face his mother-in-law, Ferdie admits he was faking his injury, and tears up the letter.",
      popularity: 2.661,
      poster_path: '/gXWTajJtS0abvXOb8ZNFCerL9dM.jpg',
      release_date: '1915-10-01',
      title: 'Fox Trot Finesse',
      video: false,
      vote_average: 5,
      vote_count: 9,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [16, 35],
      id: 57222,
      original_language: 'en',
      original_title: 'The Fox Hunt',
      overview:
        "It's morning in the English countryside and time for the gentry to participate in their favorite sport: the fox hunt. The eccentric gentlemen come in all shapes and sizes, the fat ones putting the greatest strain on the horses. The craziest things happen to the monocled hunters. One even gets knocked off his horse when it jumps over a brick wall. He shoots straight up into the air and, thanks to a parachute hidden in his clothes, makes a gentle landing. But instead of the ground, he lands on a cow. Upset by her unwanted passenger, she takes off at top speed, finally dumping him in a mud puddle, where he lands on a pig and continues his wacky ride. Meanwhile, the poor fox finally gets trapped in a hollow log. Dogs to the left of him, dogs to the right! Luckily, the beleaguered creature gets help from a certain powerful, and pungent, friend.",
      popularity: 2.516,
      poster_path: null,
      release_date: '1931-11-20',
      title: 'The Fox Hunt',
      video: false,
      vote_average: 3.7,
      vote_count: 9,
    },
    {
      adult: false,
      backdrop_path: '/omAmtwL4VFjVaEIhDUTG9OKqbLy.jpg',
      genre_ids: [28],
      id: 515445,
      original_language: 'en',
      original_title: 'UFC on Fox 29: Poirier vs. Gaethje',
      overview:
        'UFC on Fox: Poirier vs. Gaethje (also known as UFC on Fox 29) is a mixed martial arts event produced by the Ultimate Fighting Championship held on April 14, 2018, at the Gila River Arena in Glendale, Arizona.',
      popularity: 4.265,
      poster_path: '/yTGdEpD1eHdSd7nOfwFGLJu5MO7.jpg',
      release_date: '2018-04-14',
      title: 'UFC on Fox 29: Poirier vs. Gaethje',
      video: true,
      vote_average: 7,
      vote_count: 1,
    },
  ],
  total_pages: 22, // 20 items per page
  total_results: 424,
};


// below example with query: "test123", and page: 1
export const mockSearchMoviesEmptyResponse = {
  page: 1,
  results: [],
  total_results: 0,
  total_pages: 0,
};

export const mockSearchMovies401Response = {
  status_code: 7,
  status_message: 'Invalid API key: You must be granted a valid key.',
  success: false,
};

// 404 response
export const mockSearchMovies404Response = {
  success: false,
  status_code: 34,
  status_message: 'The resource you requested could not be found.',
};

// no query provided
export const mockSearchMovies422Response = {
  errors: ['query must be provided']
};
