/* eslint-disable */
/**
 * Search - Search People
 * GET /search/person API: https://developers.themoviedb.org/3/search/search-people
 *
 * response header 'cache-control': 'public, max-age=120' --- 2 minutes
 *
 * below example with query: "fox", and page: 1
 */
export const mockSearchPeopleResponse = {
  page: 1,
  // only showing 7 results for this example
  results: [
    {
      adult: false,
      gender: 1,
      id: 19537,
      known_for: [
        {
          adult: false,
          backdrop_path: '/77P56ZcL8M9Cw7FIptMIGjhNJoj.jpg',
          genre_ids: [12, 878, 28],
          id: 1858,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Transformers',
          overview:
            'Young teenager, Sam Witwicky becomes involved in the ancient struggle between two extraterrestrial factions of transforming robots – the heroic Autobots and the evil Decepticons. Sam holds the clue to unimaginable power and the Decepticons will stop at nothing to retrieve it.',
          poster_path: '/6eehp9I54syN3x753XMqjKz8M3F.jpg',
          release_date: '2007-06-27',
          title: 'Transformers',
          video: false,
          vote_average: 6.7,
          vote_count: 8074,
        },
        {
          adult: false,
          backdrop_path: '/6NV6jQymfPkPyADnyktW7PLeg7l.jpg',
          genre_ids: [878, 28, 12],
          id: 8373,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Transformers: Revenge of the Fallen',
          overview:
            "Sam Witwicky leaves the Autobots behind for a normal life. But when his mind is filled with cryptic symbols, the Decepticons target him and he is dragged back into the Transformers' war.",
          poster_path: '/pLBb0whOzVDtJvyD4DPeQyQNOqp.jpg',
          release_date: '2009-06-19',
          title: 'Transformers: Revenge of the Fallen',
          video: false,
          vote_average: 6.1,
          vote_count: 6144,
        },
        {
          adult: false,
          backdrop_path: '/eezsbzYPbYKjjh6E1XHDBNlLynh.jpg',
          genre_ids: [878, 28, 12, 35],
          id: 98566,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Teenage Mutant Ninja Turtles',
          overview:
            "The city needs heroes. Darkness has settled over New York City as Shredder and his evil Foot Clan have an iron grip on everything from the police to the politicians. The future is grim until four unlikely outcast brothers rise from the sewers and discover their destiny as Teenage Mutant Ninja Turtles. The Turtles must work with fearless reporter April and her wise-cracking cameraman Vern Fenwick to save the city and unravel Shredder's diabolical plan.",
          poster_path: '/azL2ThbJMIkts3ZMt3j1YgBUeDB.jpg',
          release_date: '2014-08-07',
          title: 'Teenage Mutant Ninja Turtles',
          video: false,
          vote_average: 5.9,
          vote_count: 5226,
        },
      ],
      known_for_department: 'Acting',
      name: 'Megan Fox',
      popularity: 6.057,
      profile_path: '/7XkWPXyoByFJorisd1W62uFj0pd.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 1014931,
      known_for: [
        {
          adult: false,
          backdrop_path: '/sVkjgKq8cwKm95LCyfrLldLbQIG.jpg',
          genre_ids: [28, 18, 14],
          id: 274857,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'King Arthur: Legend of the Sword',
          overview:
            'When the child Arthur’s father is murdered, Vortigern, Arthur’s uncle, seizes the crown. Robbed of his birthright and with no idea who he truly is, Arthur comes up the hard way in the back alleys of the city. But once he pulls the sword Excalibur from the stone, his life is turned upside down and he is forced to acknowledge his true legacy... whether he likes it or not.',
          poster_path: '/9kKXH6eJpzoFGhCbTN3FVwSQK3n.jpg',
          release_date: '2017-05-10',
          title: 'King Arthur: Legend of the Sword',
          video: false,
          vote_average: 6.5,
          vote_count: 4267,
        },
        {
          adult: false,
          backdrop_path: '/wCkGiBE4swpWwJ0C8zJLr0WNH04.jpg',
          genre_ids: [12, 28, 53],
          id: 52451,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Three Musketeers',
          overview:
            "The hot-headed young D'Artagnan along with three former legendary but now down on their luck Musketeers must unite and defeat a beautiful double agent and her villainous employer from seizing the French throne and engulfing Europe in war.",
          poster_path: '/w2LbQ8FvZiQpWvZyHljaOeiNknK.jpg',
          release_date: '2011-08-31',
          title: 'The Three Musketeers',
          video: false,
          vote_average: 5.8,
          vote_count: 1969,
        },
        {
          adult: false,
          backdrop_path: '/8kJNwEkHIg4NePpFbYFwR8NC4UM.jpg',
          genre_ids: [18, 878, 53],
          id: 228066,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Victor Frankenstein',
          overview:
            'Eccentric scientist Victor Von Frankenstein creates a grotesque creature in an unorthodox scientific experiment.',
          poster_path: '/20HjY4vlGqVjXoyap7N6TJYJTCB.jpg',
          release_date: '2015-11-10',
          title: 'Victor Frankenstein',
          video: false,
          vote_average: 5.8,
          vote_count: 1498,
        },
      ],
      known_for_department: 'Acting',
      name: 'Freddie Fox',
      popularity: 3.138,
      profile_path: '/7ZlFtKmlEea0997qT4UWMOwmy3N.jpg',
    },
    {
      adult: false,
      gender: 1,
      id: 6639,
      known_for: [
        {
          adult: false,
          backdrop_path: '/A7r8GRpvOojI2Vl5EEJfAIfzCg9.jpg',
          genre_ids: [18, 10752],
          id: 423,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'The Pianist',
          overview:
            "The true story of pianist Władysław Szpilman's experiences in Warsaw during the Nazi occupation. When the Jews of the city find themselves forced into a ghetto, Szpilman finds work playing in a café; and when his family is deported in 1942, he stays behind, works for a while as a laborer, and eventually goes into hiding in the ruins of the war-torn city.",
          poster_path: '/3DzePKMbLMIM636S6syCy3cLPqj.jpg',
          release_date: '2002-09-17',
          title: 'The Pianist',
          video: false,
          vote_average: 8.4,
          vote_count: 5869,
        },
        {
          adult: false,
          backdrop_path: '/hk0gRfvCkbvGQWLtMmpFKTEWsCJ.jpg',
          genre_ids: [14, 18, 53],
          id: 23488,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Dorian Gray',
          overview:
            "A vain London playboy offers his soul in exchange for eternal beauty in this adaptation of the chilling tale by author Oscar Wilde. Seduced into the decadent world of Lord Henry Wotton (Colin Firth), handsome young aristocrat Dorian Gray (Ben Barnes) becomes obsessed with maintaining his youthful appearance, and commissions a special portrait that will weather the winds of time while he remains forever young. When Gray's obsession spirals out of control, his desperate attempts to safeguard his secret turn his once-privileged life into a living hell.",
          poster_path: '/1dUXCi74e5E69BlVGhUhQ0YTBi.jpg',
          release_date: '2009-09-09',
          title: 'Dorian Gray',
          video: false,
          vote_average: 5.9,
          vote_count: 1537,
        },
        {
          adult: false,
          backdrop_path: '/y85RtaJCSAhkAK8FyelDvJe4Aft.jpg',
          genre_ids: [18, 35, 10749],
          id: 12225,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Cashback',
          overview:
            'After a painful breakup, Ben develops insomnia. To kill time, he starts working the late night shift at the local supermarket, where his artistic imagination runs wild.',
          poster_path: '/4CNpjxDWT0yiE3LJnbdNggoC2ze.jpg',
          release_date: '2006-05-09',
          title: 'Cashback',
          video: false,
          vote_average: 6.9,
          vote_count: 660,
        },
      ],
      known_for_department: 'Acting',
      name: 'Emilia Fox',
      popularity: 3.637,
      profile_path: '/u0SG1xsDL4eqSi14k8bFCewOVWk.jpg',
    },
    {
      adult: false,
      gender: 1,
      id: 2371446,
      known_for: [
        {
          adult: false,
          backdrop_path: '/uzvT6tYrU5SxfHe1ieimIGAqyFm.jpg',
          genre_ids: [80, 53, 18],
          id: 473033,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Uncut Gems',
          overview:
            'A charismatic New York City jeweler always on the lookout for the next big score makes a series of high-stakes bets that could lead to the windfall of a lifetime. Howard must perform a precarious high-wire act, balancing business, family, and encroaching adversaries on all sides in his relentless pursuit of the ultimate win.',
          poster_path: '/6XN1vxHc7kUSqNWtaQKN45J5x2v.jpg',
          release_date: '2019-08-30',
          title: 'Uncut Gems',
          video: false,
          vote_average: 7.1,
          vote_count: 2551,
        },
        {
          adult: false,
          genre_ids: [],
          id: 682184,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Money on the Street: The Making of Uncut Gems',
          overview:
            'A behind the scenes look at Uncut Gems (2019) by the Safdie Brothers with interviews from the cast and more.',
          poster_path: '/tfhj1X9knwHyPjYthsy4vg5WcO7.jpg',
          release_date: '2020-03-10',
          title: 'Money on the Street: The Making of Uncut Gems',
          video: false,
          vote_average: 6.3,
          vote_count: 3,
        },
        {
          adult: false,
          genre_ids: [18],
          id: 670129,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'PVT CHAT',
          overview:
            'Jack is an internet gambler living in NYC. After the death of his roommate, he becomes fixated on Scarlet - a cam girl from San Francisco. His obsession reaches a boiling point when fantasy materializes in reality and Jack sees Scarlet on a rainy NYC Chinatown street.',
          poster_path: '/zpUnsHBGXy9Y1u3Xh3yHCTBGEc6.jpg',
          release_date: '2020-08-21',
          title: 'PVT CHAT',
          video: false,
          vote_average: 4,
          vote_count: 1,
        },
      ],
      known_for_department: 'Acting',
      name: 'Julia Fox',
      popularity: 4.629,
      profile_path: '/AwipgBalCBiOfwXKssxM0NQlz33.jpg',
    },
    {
      adult: false,
      gender: 1,
      id: 2535,
      known_for: [
        {
          adult: false,
          backdrop_path: '/lVy5Zqcty2NfemqKYbVJfdg44rK.jpg',
          genre_ids: [28, 80],
          id: 24,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Kill Bill: Vol. 1',
          overview:
            'An assassin is shot by her ruthless employer, Bill, and other members of their assassination circle – but she lives to plot her vengeance.',
          poster_path: '/v7TaX8kXMXs5yFFGR41guUDNcnB.jpg',
          release_date: '2003-10-10',
          title: 'Kill Bill: Vol. 1',
          video: false,
          vote_average: 8,
          vote_count: 12594,
        },
        {
          adult: false,
          backdrop_path: '/70EtzaGfO2d8X5n8SLI4s61KuJh.jpg',
          genre_ids: [28, 80, 53],
          id: 393,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Kill Bill: Vol. 2',
          overview:
            "The Bride unwaveringly continues on her roaring rampage of revenge against the band of assassins who had tried to kill her and her unborn child. She visits each of her former associates one-by-one, checking off the victims on her Death List Five until there's nothing left to do … but kill Bill.",
          poster_path: '/2yhg0mZQMhDyvUQ4rG1IZ4oIA8L.jpg',
          release_date: '2004-04-16',
          title: 'Kill Bill: Vol. 2',
          video: false,
          vote_average: 7.9,
          vote_count: 10082,
        },
        {
          adult: false,
          backdrop_path: '/uw4SnKFZ453Gxmj5XR5Susj8TNo.jpg',
          genre_ids: [28, 12, 878],
          id: 602,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Independence Day',
          overview:
            "On July 2, a giant alien mothership enters orbit around Earth and deploys several dozen saucer-shaped 'destroyer' spacecraft that quickly lay waste to major cities around the planet. On July 3, the United States conducts a coordinated counterattack that fails. On July 4, a plan is devised to gain access to the interior of the alien mothership in space, in order to plant a nuclear missile.",
          poster_path: '/p0BPQGSPoSa8Ml0DAf2mB2kCU0R.jpg',
          release_date: '1996-06-25',
          title: 'Independence Day',
          video: false,
          vote_average: 6.8,
          vote_count: 6933,
        },
      ],
      known_for_department: 'Acting',
      name: 'Vivica A. Fox',
      popularity: 4.655,
      profile_path: '/rTxble6xvCSEOP2s7Qm2svu92HH.jpg',
    },
    {
      adult: false,
      gender: 2,
      id: 521,
      known_for: [
        {
          adult: false,
          backdrop_path: '/fq3wyOs1RHyz2yfzsb4sck7aWRG.jpg',
          genre_ids: [12, 35, 878, 10751],
          id: 105,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Back to the Future',
          overview:
            "Eighties teenager Marty McFly is accidentally sent back in time to 1955, inadvertently disrupting his parents' first meeting and attracting his mother's romantic interest. Marty must repair the damage to history by rekindling his parents' romance and - with the help of his eccentric inventor friend Doc Brown - return to 1985.",
          poster_path: '/xlBivetfrtF84Yx0zISShnNtHYe.jpg',
          release_date: '1985-07-03',
          title: 'Back to the Future',
          video: false,
          vote_average: 8.3,
          vote_count: 14274,
        },
        {
          adult: false,
          backdrop_path: '/skQN2UMQKQnOTmwplcYMx6ZF4jS.jpg',
          genre_ids: [12, 35, 10751, 878],
          id: 165,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Back to the Future Part II',
          overview:
            'Marty and Doc are at it again in this wacky sequel to the 1985 blockbuster as the time-traveling duo head to 2015 to nip some McFly family woes in the bud. But things go awry thanks to bully Biff Tannen and a pesky sports almanac. In a last-ditch attempt to set things straight, Marty finds himself bound for 1955 and face to face with his teenage parents -- again.',
          poster_path: '/hQq8xZe5uLjFzSBt4LanNP7SQjl.jpg',
          release_date: '1989-11-22',
          title: 'Back to the Future Part II',
          video: false,
          vote_average: 7.7,
          vote_count: 9116,
        },
        {
          adult: false,
          backdrop_path: '/nh6mrOtIvD8MMC6JQIzwNDZi2G0.jpg',
          genre_ids: [12, 35, 878],
          id: 196,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Back to the Future Part III',
          overview:
            'The final installment of the Back to the Future trilogy finds Marty digging the trusty DeLorean out of a mineshaft and looking for Doc in the Wild West of 1885. But when their time machine breaks down, the travelers are stranded in a land of spurs. More problems arise when Doc falls for pretty schoolteacher Clara Clayton, and Marty tangles with Buford Tannen.',
          poster_path: '/crzoVQnMzIrRfHtQw0tLBirNfVg.jpg',
          release_date: '1990-05-25',
          title: 'Back to the Future Part III',
          video: false,
          vote_average: 7.4,
          vote_count: 7310,
        },
      ],
      known_for_department: 'Acting',
      name: 'Michael J. Fox',
      popularity: 4.44,
      profile_path: '/2JB4FMgQmnhbBlQ4SxWFN9EIVDi.jpg',
    },
    {
      adult: false,
      gender: 1,
      id: 1849379,
      known_for: [
        {
          backdrop_path: '/w6t8mFlyB6JKcEGm3cojvylIc5O.jpg',
          first_air_date: '2005-08-04',
          genre_ids: [35],
          id: 2710,
          media_type: 'tv',
          name: "It's Always Sunny in Philadelphia",
          origin_country: ['US'],
          original_language: 'en',
          original_name: "It's Always Sunny in Philadelphia",
          overview:
            'Four egocentric friends who run a neighborhood Irish pub in Philadelphia try to find their way through the adult world of work and relationships. Unfortunately, their warped views and precarious judgments often lead them to trouble, creating a myriad of uncomfortable situations that usually only get worse before they get better.',
          poster_path: '/xX3vAWdCb828T48HM9OvvD0p4PC.jpg',
          vote_average: 8.2,
          vote_count: 529,
        },
        {
          adult: false,
          backdrop_path: '/pl5gevwmEM2Fc5aOoPXxK9TQURm.jpg',
          genre_ids: [14, 27],
          id: 384978,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Puppet Master: Axis Termination',
          overview:
            'In PUPPET MASTER XI - AXIS TERMINATION, the final chapter of the AXIS Saga, we find our heroic band of lethal puppets-BLADE, PINHEAD, TUNNELER, JESTER, SIX SHOOTER, and LEECH WOMAN, joining forces with a secret team of Allied Operatives, all masters of psychic powers, as they face off together against a new bunch of evil Nazi adversaries and their collection of vicious Axis Puppets in a showdown that will decide the future of the free world.',
          poster_path: '/hE4wGidAJ2yppEkZsY7QmWHJaWR.jpg',
          release_date: '2017-09-15',
          title: 'Puppet Master: Axis Termination',
          video: false,
          vote_average: 5.2,
          vote_count: 21,
        },
        {
          adult: false,
          backdrop_path: '/wAHrbzmGeybyHGHRKS8G4lLeL32.jpg',
          genre_ids: [27],
          id: 633159,
          media_type: 'movie',
          original_language: 'en',
          original_title: 'Art of the Dead',
          overview:
            'When a man purchases a collection of seven paintings to hang in his wealthy estate, he has no idea what horrors he has unleashed for himself and his family.',
          poster_path: '/l3CCtoklH4uPn5zFgJZhastTxZ9.jpg',
          release_date: '2019-10-01',
          title: 'Art of the Dead',
          video: false,
          vote_average: 5.7,
          vote_count: 6,
        },
      ],
      known_for_department: 'Acting',
      name: 'Tania Fox',
      popularity: 2.263,
      profile_path: '/nLjOVgNxvUYGeuq130N5OmW3Gy.jpg',
    },
    // { ... }
  ],
  total_pages: 49, // 20 items per page
  total_results: 963,
};

// below example with query: "test123", and page: 1
export const mockSearchPeopleEmptyResponse = {
  page: 1,
  results: [],
  total_results: 0,
  total_pages: 0,
};

export const mockSearchPeople401Response = {
  status_code: 7,
  status_message: 'Invalid API key: You must be granted a valid key.',
  success: false,
};

// 404 response
export const mockSearchPeople404Response = {
  success: false,
  status_code: 34,
  status_message: 'The resource you requested could not be found.',
};

// no query provided
export const mockSearchPeople422Response = {
  errors: ['query must be provided']
};

// knownFor item inside a person obj
export const mockSearchPeopleKnownForItem = {
  movieKnownFor: {
    adult: false,
    backdrop_path: '/pl5gevwmEM2Fc5aOoPXxK9TQURm.jpg',
    genre_ids: [14, 27],
    id: 384978,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Puppet Master: Axis Termination',
    overview:
      'In PUPPET MASTER XI - AXIS TERMINATION, the final chapter of the AXIS Saga, we find our heroic band of lethal puppets-BLADE, PINHEAD, TUNNELER, JESTER, SIX SHOOTER, and LEECH WOMAN, joining forces with a secret team of Allied Operatives, all masters of psychic powers, as they face off together against a new bunch of evil Nazi adversaries and their collection of vicious Axis Puppets in a showdown that will decide the future of the free world.',
    poster_path: '/hE4wGidAJ2yppEkZsY7QmWHJaWR.jpg',
    release_date: '2017-09-15',
    title: 'Puppet Master: Axis Termination',
    video: false,
    vote_average: 5.2,
    vote_count: 21,
  },
  tvShowKnownFor: {
    backdrop_path: '/w6t8mFlyB6JKcEGm3cojvylIc5O.jpg',
    first_air_date: '2005-08-04',
    genre_ids: [35],
    id: 2710,
    media_type: 'tv',
    name: "It's Always Sunny in Philadelphia",
    origin_country: ['US'],
    original_language: 'en',
    original_name: "It's Always Sunny in Philadelphia",
    overview:
      'Four egocentric friends who run a neighborhood Irish pub in Philadelphia try to find their way through the adult world of work and relationships. Unfortunately, their warped views and precarious judgments often lead them to trouble, creating a myriad of uncomfortable situations that usually only get worse before they get better.',
    poster_path: '/xX3vAWdCb828T48HM9OvvD0p4PC.jpg',
    vote_average: 8.2,
    vote_count: 529,
  },
};